<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="Run on Chrome"
           tests="7"
           failures="1"
           errors="0"
           skipped="0"
           time="47.741">
  <properties />
            <testcase name="TC_06_Check_Slant_Bet" time="15.431" classname="com.game789d.club.homepage_with_789dclub">
                <failure type="java.lang.AssertionError"
                  message="expected [true] but found [false]"
              >
<![CDATA[java.lang.AssertionError: expected [true] but found [false]
  org.testng.Assert.fail(Assert.java:96)
  org.testng.Assert.failNotEquals(Assert.java:776)
  org.testng.Assert.assertTrue(Assert.java:44)
  org.testng.Assert.assertTrue(Assert.java:54)
  commons.AbstractTest.checkTrue(AbstractTest.java:68)
  commons.AbstractTest.verifyTrue(AbstractTest.java:80)
  com.game789d.club.homepage_with_789dclub.TC_06_Check_Slant_Bet(homepage_with_789dclub.java:321)
  java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
  java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  java.base/java.lang.reflect.Method.invoke(Method.java:568)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
  org.testng.TestRunner.privateRun(TestRunner.java:648)
  org.testng.TestRunner.run(TestRunner.java:505)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
  org.testng.SuiteRunner.run(SuiteRunner.java:364)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
  org.testng.TestNG.runSuites(TestNG.java:1049)
  org.testng.TestNG.run(TestNG.java:1017)
  org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
  org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
  org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
      </failure>

          </testcase>
  
  
            <testcase name="TC_05_Check_History_Bet_And_Cancel" time="3.782" classname="com.game789d.club.homepage_with_789dclub" />
                <testcase name="TC_01_Check_Betting" time="12.193" classname="com.game789d.club.homepage_with_789dclub" />
                <testcase name="TC_04_Check_Cancle_Bet" time="0.394" classname="com.game789d.club.homepage_with_789dclub" />
                <testcase name="TC_07_Check_Slant_Bet" time="0.003" classname="com.game789d.club.homepage_with_789dclub" />
                <testcase name="TC_03_Check_Bet_Not_Successful" time="4.668" classname="com.game789d.club.homepage_with_789dclub" />
                <testcase name="TC_02_Check_Cancel_Bet_Successful" time="11.270" classname="com.game789d.club.homepage_with_789dclub" />
      
</testsuite>
