<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-MC950J7" failures="1" tests="7" name="com.game789d.club.homepage_with_789dclub" time="47.741" errors="0" timestamp="16 Nov 2022 09:50:26 GMT" skipped="0">
  <testcase classname="com.game789d.club.homepage_with_789dclub" name="TC_05_Check_History_Bet_And_Cancel" time="3.782"/>
  <testcase classname="com.game789d.club.homepage_with_789dclub" name="TC_01_Check_Betting" time="12.193"/>
  <testcase classname="com.game789d.club.homepage_with_789dclub" name="TC_04_Check_Cancle_Bet" time="0.394"/>
  <testcase classname="com.game789d.club.homepage_with_789dclub" name="TC_06_Check_Slant_Bet" time="15.431">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at commons.AbstractTest.checkTrue(AbstractTest.java:68)
at commons.AbstractTest.verifyTrue(AbstractTest.java:80)
at com.game789d.club.homepage_with_789dclub.TC_06_Check_Slant_Bet(homepage_with_789dclub.java:321)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- TC_06_Check_Slant_Bet -->
  <testcase classname="com.game789d.club.homepage_with_789dclub" name="TC_07_Check_Slant_Bet" time="0.003"/>
  <testcase classname="com.game789d.club.homepage_with_789dclub" name="TC_03_Check_Bet_Not_Successful" time="4.668"/>
  <testcase classname="com.game789d.club.homepage_with_789dclub" name="TC_02_Check_Cancel_Bet_Successful" time="11.270"/>
</testsuite> <!-- com.game789d.club.homepage_with_789dclub -->
